<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-MDM1H7HV" failures="1" tests="1" name="Command line test" time="10.489" errors="0" timestamp="2020-03-06T14:20:08 ART">
  <testcase classname="testCases.SelectTest" name="searchByInStock" time="1.812">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testCases.SelectTest.searchByInStock(SelectTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- searchByInStock -->
  <testcase classname="testCases.SearchTest" name="searchWithResults" time="0.0">
    <ignored/>
  </testcase> <!-- searchWithResults -->
  <testcase classname="testCases.SectionsTest" name="womanSection" time="0.0">
    <ignored/>
  </testcase> <!-- womanSection -->
  <testcase classname="testCases.SelectTest" name="searchByNameAtoZ" time="0.0">
    <ignored/>
  </testcase> <!-- searchByNameAtoZ -->
  <testcase classname="testCases.SearchTest" name="searchWithNoResults" time="0.0">
    <ignored/>
  </testcase> <!-- searchWithNoResults -->
  <testcase classname="testCases.SelectTest" name="searchByLowestFirst" time="0.0">
    <ignored/>
  </testcase> <!-- searchByLowestFirst -->
</testsuite> <!-- Command line test -->
